# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Complexe
                                 A QGIS plugin
 Assistant complexe
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import json
import subprocess

from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QInputDialog, QMessageBox, QDialog, QListWidgetItem, QComboBox, QFileDialog, QProgressBar, \
    QApplication
from PyQt5.uic import loadUi
from qgis.core import QgsProject,QgsExpression
from qgis.PyQt.QtGui import QIcon
import os.path
from pathlib import Path

from .fonction import *


REP_REQUETES = "requêtes"

TITRE = "Requêtes"
VERSION = "0.1"

def log(message):
    """
    Écrit un message dans le fichier de log avec un horodatage.
    Le fichier est ouvert en mode append pour ne pas écraser les données.
    """
    fic_log = os.path.join(os.path.dirname(__file__), "log.txt")
    with open(fic_log, "a", encoding="utf-8") as f:
        f.write(f"{message}\n")

class Requete:
    def __init__(self, iface):

        self.iface = iface

    def get_dossier_requetes(self):
        return self._rep_requete

    def set_dossier_requetes(self) -> str:
        self._rep_requete = os.path.join(os.path.dirname(__file__),REP_REQUETES)

    def get_list_requete_unique(self):
        dossier = Path(self.get_dossier_requetes())
        list_requete = [f.name for f in dossier.iterdir() if f.is_file()]
        return list_requete

    def ini_combo_requete(self):
        self.dlg_requete_unique = QDialog()
        self.dlg_requete_unique.setParent(self.iface.mainWindow())
        loadUi(os.path.join(os.path.dirname(__file__),"requete_unique.ui"), self.dlg_requete_unique)
        self.dlg_requete_unique.setWindowTitle("Exécuter une requête")
        self.dlg_requete_unique.setWindowFlags(Qt.Dialog | Qt.WindowTitleHint | Qt.WindowCloseButtonHint)

        self.dlg_requete_unique.progressBar.hide()

        liste_req = self.get_list_requete_unique()
        self.dlg_requete_unique.comboBox_requetes.addItems(liste_req)
        self.dlg_requete_unique.pushButtonExecuter.clicked.connect(self.on_run_requete)
        self.dlg_requete_unique.pushButton_tester.clicked.connect(self.on_test_requetes)
        self.dlg_requete_unique.pushButtonLog.clicked.connect(self.on_afficher_log)

    def on_test_requetes(self):
        # print(self.get_dossier_requetes())
        # self.dlg_requete_unique.progressBar.show()
        self.on_run_requete(all = True)
        # self.dlg_requete_unique.progressBar.hide()

    def get_mode_requete(self,fichier_requete):
        mode = ""
        # test si le fichier est enregistré en unicode ou autre
        try:
            with open(fichier_requete, "r", encoding="utf-8") as f:
                for ligne in f:
                    ligne = ligne.strip()
                    # Vérifie si la ligne contient un commentaire commençant par --
                    if ligne.startswith("--MODE="):
                        # Récupère ce qu'il y a après --
                        contenu = ligne[7:].strip()
                        mode = contenu
        except UnicodeDecodeError:
            with open(fichier_requete, "r", encoding="latin-1") as f:
                for ligne in f:
                    ligne = ligne.strip()
                    # Vérifie si la ligne contient un commentaire commençant par --
                    if ligne.startswith("--MODE="):
                        # Récupère ce qu'il y a après --MODE=
                        contenu = ligne[7:].strip()
                        mode = contenu
        return mode


    def get_list_to_create(self,fichier_requete):
        list_to_create = []
        with open(fichier_requete, "r", encoding="utf-8") as f:
            for ligne in f:
                ligne = ligne.strip()
                # Vérifie si la ligne contient un commentaire commençant par --
                if ligne.startswith("--LISTE="):
                    # Récupère ce qu'il y a après --LISTE=
                    contenu = ligne[8:].strip()
                    list_to_create = [item.strip() for item in contenu.split(",")]
        return list_to_create

    def get_layer_request(self,fichier_requete):
        layer = ""
        with open(fichier_requete, "r", encoding="utf-8") as f:
            for ligne in f:
                ligne = ligne.strip()
                # Vérifie si la ligne contient un commentaire commençant par --
                if ligne.startswith("--LAYER="):
                    # Récupère ce qu'il y a après --LAYER=
                    contenu = ligne[8:].strip()
                    layer = contenu
        return layer




    def on_run_requete(self, all = False):
        if all:
            fichiers  = self.get_list_requete_unique()
        else :
            fichier_unique = self.dlg_requete_unique.comboBox_requetes.currentText()
            fichiers  = [fichier_unique]

        self.dlg_requete_unique.progressBar.setRange(0, len(fichiers))
        self.dlg_requete_unique.progressBar.setValue(0)
        self.dlg_requete_unique.progressBar.show()
        QApplication.processEvents()
        comp = 1
        compt_requete_ok = 0
        for fichier in fichiers:
            self.dlg_requete_unique.progressBar.setValue(comp)
            fic_req_sel = os.path.join(self.get_dossier_requetes(), fichier)
            try:
                with open(fic_req_sel, "r", encoding="utf-8") as f:
                    requete = f.read().strip()
            except UnicodeDecodeError:
                with open(fic_req_sel, "r", encoding="latin-1") as f:
                    requete = f.read().strip()
            exp = QgsExpression(requete)
            if exp.hasParserError():
                erreur = exp.parserErrorString()
                if erreur.strip() == "syntax error, unexpected LT":
                    log(f"{comp}-{fichier} : ERREUR: les caractères < et > sont interdits")
                else:
                    log(f"{comp}-{fichier} : ERREUR: \t{erreur}")
            else:
                mode = self.get_mode_requete(fic_req_sel)
                if mode == "SELECT":
                    try:
                        layer_name = self.get_layer_request(fic_req_sel)
                        layers = QgsProject.instance().mapLayersByName(layer_name)
                        if not layers:
                            log(f"{comp}-{fichier} : ERREUR: couche '{layer_name}' introuvable")
                        else:
                            layer = layers[0]
                            layer.selectByExpression(requete)
                            nb_sel = layer.selectedFeatureCount()
                            log(f"{comp}-{fichier} : OK ({nb_sel} entités sélectionnées)")
                            compt_requete_ok += 1
                            # creation d'une liste
                            nom_liste = self.get_list_to_create(fic_req_sel)
                            if nom_liste != []:
                                print("creation de la liste : ",nom_liste)
                                fichier_liste = os.path.join(get_dossier_listes(), f"{nom_liste}.json")
                                dico = get_dico_selection(layer)
                                with open(fichier_liste, "w", encoding="utf-8") as f:
                                    json.dump(dico, f, indent=2, ensure_ascii=False)



                    except Exception as e:
                        log(f"{comp}-{fichier} : ERREUR inconnue : {str(e)}")
            comp += 1
        log(f"===== requêtes traitées, {compt_requete_ok} réussies, {comp-1-compt_requete_ok} en erreur ======")
        self.dlg_requete_unique.progressBar.hide()
        # self.dlg_requete_unique.accept()

    def run_requete_enchaine(self,requete):
        print("execution de requete enchainée : ",requete)

    def initGui(self):
        pass

    def unload(self):
        pass

    def on_afficher_log(self):
        fichier = os.path.join(os.path.dirname(__file__), "log.txt")
        if not os.path.isfile(fichier):
            QMessageBox.warning(None,"Information","Le fichier de log est introuvable", )
        else:
            subprocess.Popen(['start', '', fichier], shell=True)

    def run(self):
        # suppression du log
        if os.path.exists(os.path.join(os.path.dirname(__file__), "log.txt")):
            os.remove(os.path.join(os.path.dirname(__file__), "log.txt"))

        project = QgsProject.instance()
        if not project.fileName():
            QMessageBox.warning(None,"Avertissement","Aucun projet chargé")
            return

        if not os.path.exists(os.path.join(os.path.dirname(__file__),REP_REQUETES)):
            QMessageBox.warning(None,"Avertissement","Aucune requête disponible")
            return

        self.set_dossier_requetes()

        list_type_requete = ["Requête unique","Requête enchainée" ]
        dialog = QInputDialog()
        dialog.setComboBoxItems(list_type_requete)
        dialog.setWindowTitle("Choisir ...")
        dialog.setLabelText("Type de requête :")
        chemin_icon = os.path.join(os.path.dirname(__file__),"icons","icon_principal.png")
        dialog.setWindowIcon(QIcon(chemin_icon))
        choix = ""

        if dialog.exec_():
            choix = dialog.textValue()

        # requete unique
        if choix == list_type_requete[0]:
            self.ini_combo_requete()
            self.dlg_requete_unique.progressBar.setValue(0)
            #
            self.dlg_requete_unique.show()

        # requetes enchainées
        elif choix == list_type_requete[1]:
            # Ouvre une boîte de dialogue pour choisir un fichier
            fichier, _ = QFileDialog.getOpenFileName(
                None,  # parent
                "Sélectionnez un fichier",  # titre
                self.get_dossier_requetes(),  # répertoire initial
                "Fichiers text (*.txt)"  # filtres
            )
            self.run_requete_enchaine(fichier)


        # # Run the dialog event loop
        # result = self.dlg.exec_()
        # # See if OK was pressed
        # if result:
        #     # Do something useful here - delete the line containing pass and
        #     # substitute with your code.
        #     pass
