# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Complexe
                                 A QGIS plugin
 Assistant complexe
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import json
import re
import subprocess
import sqlite3
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QInputDialog, QMessageBox, QDialog, QFileDialog,QApplication
from PyQt5.uic import loadUi
from qgis.core import QgsProject,QgsExpression,QgsProviderRegistry,QgsVectorLayer,QgsFeatureRequest
from qgis.PyQt.QtGui import QIcon
import os.path
from pathlib import Path

from .fonction import *


REP_REQUETES = "requêtes"
CLEABS = "cleabs"

TITRE = "Requêtes"
VERSION = "0.1"

def log(message):
    """
    Écrit un message dans le fichier de log avec un horodatage.
    Le fichier est ouvert en mode append pour ne pas écraser les données.
    """
    fic_log = os.path.join(os.path.dirname(__file__), "log.txt")
    with open(fic_log, "a", encoding="utf-8") as f:
        f.write(f"{message}\n")

class Requete:
    def __init__(self, iface):

        self.iface = iface

    def get_dossier_requetes(self):
        return self._rep_requete

    def set_dossier_requetes(self) -> str:
        self._rep_requete = os.path.join(os.path.dirname(__file__),REP_REQUETES)

    def get_list_requete_unique(self):
        dossier = Path(self.get_dossier_requetes())
        list_requete = [f.name for f in dossier.iterdir() if f.is_file()]
        return list_requete

    def ini_combo_requete(self):
        self.dlg_requete_unique = QDialog()
        self.dlg_requete_unique.setParent(self.iface.mainWindow())
        loadUi(os.path.join(os.path.dirname(__file__),"requete_unique.ui"), self.dlg_requete_unique)
        self.dlg_requete_unique.setWindowTitle("Exécuter une requête")
        self.dlg_requete_unique.setWindowFlags(Qt.Dialog | Qt.WindowTitleHint | Qt.WindowCloseButtonHint)

        self.dlg_requete_unique.progressBar.hide()

        liste_req = self.get_list_requete_unique()
        self.dlg_requete_unique.comboBox_requetes.addItems(liste_req)

        # self.dlg_requete_unique.pushButtonExecuter.clicked.connect(self.on_run_requete)
        # self.dlg_requete_unique.pushButtonExecuter.clicked.connect(self.on_run_requete_via_python)
        self.dlg_requete_unique.pushButtonExecuter.clicked.connect(self.on_run_requete_via_ogr)


        self.dlg_requete_unique.pushButton_tester.clicked.connect(self.on_test_requetes)
        self.dlg_requete_unique.pushButtonLog.clicked.connect(self.on_afficher_log)

    def on_test_requetes(self):
        # print(self.get_dossier_requetes())
        # self.dlg_requete_unique.progressBar.show()
        self.on_run_requete_via_ogr(all = True)
        # self.dlg_requete_unique.progressBar.hide()


    def on_run_requete_via_python(self, all = False):
        path_sqlite = QgsProject.instance().fileName().replace(".qgz", "_espaceco.sqlite")
        if all:
            fichiers = self.get_list_requete_unique()
        else:
            fichier_unique = self.dlg_requete_unique.comboBox_requetes.currentText()
            fichiers = [fichier_unique]

        self.dlg_requete_unique.progressBar.setRange(0, len(fichiers))
        self.dlg_requete_unique.progressBar.setValue(0)
        self.dlg_requete_unique.progressBar.show()
        QApplication.processEvents()
        comp = 1
        compt_requete_ok = 0

        for fichier in fichiers:
            self.dlg_requete_unique.progressBar.setValue(comp)
            requete = self.load_requete(fichier)
            # fic_req_sel = os.path.join(self.get_dossier_requetes(), fichier)
            # try:
            #     with open(fic_req_sel, "r", encoding="utf-8") as f:
            #         requete = f.read().strip()
            # except UnicodeDecodeError:
            #     with open(fic_req_sel, "r", encoding="latin-1") as f:
            #         requete = f.read().strip()

            conn = sqlite3.connect(path_sqlite)
            print("OK : connexion ouverte")
            conn.enable_load_extension(True)
            # Charger SpatiaLite
            try:
                conn.load_extension("mod_spatialite")
                print("OK : SpatiaLite chargé")
            except Exception as e:\
                print("ERREUR chargement SpatiaLite :", e)
            cur = conn.cursor()
            cur.execute(requete)
            print(cur.fetchall())
            conn.close()

            comp += 1
            self.dlg_requete_unique.progressBar.hide()

            # return rows
        log(f"===== requêtes traitées, {compt_requete_ok} réussies, {comp - 1 - compt_requete_ok} en erreur ======")

    def on_run_requete_via_ogr(self, all = False):
        path_sqlite = QgsProject.instance().fileName().replace(".qgz", "_espaceco.sqlite")
        provider = QgsProviderRegistry.instance().providerMetadata("ogr")
        conn = provider.createConnection(path_sqlite, {})
        if all:
            fichiers = self.get_list_requete_unique()
        else:
            fichier_unique = self.dlg_requete_unique.comboBox_requetes.currentText()
            fichiers = [fichier_unique]

        self.dlg_requete_unique.progressBar.setRange(0, len(fichiers))
        self.dlg_requete_unique.progressBar.setValue(0)
        self.dlg_requete_unique.progressBar.show()
        QApplication.processEvents()
        comp = 1
        compt_requete_ok = 0
        list_requete_bonne = []

        for fichier in fichiers:
            self.dlg_requete_unique.progressBar.setValue(comp)
            requete = self.load_requete(fichier)
            try:

                # réécrire la requete pour remplacer option(select) par une selection dans la table des couches
                mode_select = False
                old_requete = requete
                requete = requete.replace("Options(Select)","")
                if requete != old_requete:
                    mode_select = True
                # idem pour creation de liste
                # ......

                conn = sqlite3.connect(path_sqlite)
                try:
                    conn.enable_load_extension(True)
                except Exception as e: \
                        print("ERREUR chargement SpatiaLite :", e)
                conn.load_extension("mod_spatialite")
                cur = conn.cursor()
                cur.execute(requete)
                rows = cur.fetchall()

                if mode_select:
                    layer_match = re.search(r'FROM\s+([^\s]+)', requete, re.IGNORECASE)
                    layer = QgsProject.instance().mapLayersByName(layer_match.group(1))[0]
                    # print("layer = ",layer.group(1))

                    # récupérer les noms des colonnes
                    col_names = [desc[0] for desc in cur.description]
                    # trouver l'index de l'identifiant
                    if "cleabs" in col_names:
                        id_cleabs = col_names.index("cleabs")
                        cleabs = [row[id_cleabs] for row in rows]
                        list_id = self.get_ids_from_cleabs(layer,cleabs)
                        layer.selectByIds(list_id)

                print(f"{fichier} : nombre d'entités trouvées = {len(rows)}")
                log(f"{comp}-{fichier} : OK ({len(rows)} entités trouvées)")
                list_requete_bonne.append(fichier)
                compt_requete_ok += 1
            except Exception as e:
                print("Erreur SQL :", e)
                log(f"{comp}-{fichier} : ERREUR:\n {str(e)}\n")
            comp += 1
        log(f"===== requêtes traitées, {compt_requete_ok} réussies, {comp - 1 - compt_requete_ok} en erreur ======")
        for fic_req in list_requete_bonne:
            log(f" Requêtes ok =  {fic_req}")
        self.dlg_requete_unique.progressBar.hide()

    def get_ids_from_cleabs(self,layer: QgsVectorLayer, cleabs_list: list[str]) -> list:
        """
            Retourne la liste des ids correspondant aux cleabs donées
            :param layer: QgsVectorLayer
            :param cleabs_list: Liste des valeurs à rechercher dans le champ CLEABS
            :return: list[int]
            """
        # ids = [feature.id() for feature in layer.getFeatures() if feature[CLEABS] in cleabs]
        if not cleabs_list:
            return []

        # exemple : "cleabs" IN ('TRONROUT0000000010822670', 'TRONROUT0000000294135247')
        expr = QgsExpression(f'"{CLEABS}" IN ({", ".join(f"\'{v}\'" for v in cleabs_list)})')
        request = QgsFeatureRequest(expr)
        ids = [feat.id() for feat in layer.getFeatures(request)]
        return ids

    def load_requete(self,fichier):
        fic_req_sel = os.path.join(self.get_dossier_requetes(), fichier)
        try:
            with open(fic_req_sel, "r", encoding="utf-8") as f:
                requete = f.read().strip()
        except UnicodeDecodeError:
            with open(fic_req_sel, "r", encoding="latin-1") as f:
                requete = f.read().strip()
        return requete



    def run_requete_enchaine(self,requete):
        print("execution de requete enchainée : ",requete)

    def initGui(self):
        pass

    def unload(self):
        pass

    def on_afficher_log(self):
        fichier = os.path.join(os.path.dirname(__file__), "log.txt")
        if not os.path.isfile(fichier):
            QMessageBox.warning(None,"Information","Le fichier de log est introuvable", )
        else:
            subprocess.Popen(['start', '', fichier], shell=True)

    def run(self):
        # suppression du log
        if os.path.exists(os.path.join(os.path.dirname(__file__), "log.txt")):
            os.remove(os.path.join(os.path.dirname(__file__), "log.txt"))

        project = QgsProject.instance()
        if not project.fileName():
            QMessageBox.warning(None,"Avertissement","Aucun projet chargé")
            return

        if not os.path.exists(os.path.join(os.path.dirname(__file__),REP_REQUETES)):
            QMessageBox.warning(None,"Avertissement","Aucune requête disponible")
            return

        self.set_dossier_requetes()

        list_type_requete = ["Requête unique","Requête enchainée" ]
        dialog = QInputDialog()
        dialog.setComboBoxItems(list_type_requete)
        dialog.setWindowTitle("Choisir ...")
        dialog.setLabelText("Type de requête :")
        chemin_icon = os.path.join(os.path.dirname(__file__),"icons","icon_principal.png")
        dialog.setWindowIcon(QIcon(chemin_icon))
        choix = ""

        if dialog.exec_():
            choix = dialog.textValue()

        # requete unique
        if choix == list_type_requete[0]:
            self.ini_combo_requete()
            self.dlg_requete_unique.progressBar.setValue(0)
            #
            self.dlg_requete_unique.show()

        # requetes enchainées
        elif choix == list_type_requete[1]:
            # Ouvre une boîte de dialogue pour choisir un fichier
            fichier, _ = QFileDialog.getOpenFileName(
                None,  # parent
                "Sélectionnez un fichier",  # titre
                self.get_dossier_requetes(),  # répertoire initial
                "Fichiers text (*.txt)"  # filtres
            )
            self.run_requete_enchaine(fichier)


        # # Run the dialog event loop
        # result = self.dlg.exec_()
        # # See if OK was pressed
        # if result:
        #     # Do something useful here - delete the line containing pass and
        #     # substitute with your code.
        #     pass
